name: Build EBOOT.PBP

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: pspdev/pspdev:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug PSP SDK
        run: |
          echo "=== psp-config ==="
          which psp-config || true

          echo "=== PSPDEV PATH ==="
          psp-config --pspdev-path || true

          echo "=== PSPSDK PATH ==="
          psp-config --pspsdk-path || true

          echo "=== Looking for build.mak ==="
          find /usr/local/pspdev -name "build.mak"

      - name: Build
        run: |
          make clean
          make

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PSP-Receiver-EBOOT
          path: |
            EBOOT.PBP
            *.elf
            *.prx
            *.map
